### ISSUE TITLE
Add DELETE filing endpoint

### ISSUE THREAD

**Issue by jcadam14** [cfpb/regtech-cleanup-api#4]
Add an endpoint to delete a filing.  Use the filing-api GET/POST filing as a template for the endpoint:
`@router.get("/institutions/{lei}/filings/{period_code}"`

The endpoint should
- Check that the LEI has 'E2ETEST' in the 6-12 index of the string, otherwise it's ignored
- Delete all the model objects related to that LEI (SubmissionDAOs, UserActionDAOs, etc)
- Delete S3 objects

Feel free to break this into individual stories for each thing being deleted.

**Comment by guffee23** [comment]
Broke this down into smaller tasks. This is dependent on #11, #12, #13.
